version: 2

jobs:

    # The build job
    build:
        working_directory: ~/project
        docker:
            - image: circleci/node:15.6.0-browsers

        steps:

            # Checkout the code from the branch into the working_directory
            - checkout

            # Log the current branch
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}

            # Restore local dependencies from cache
            - restore_cache:
                keys:
                - v1-dependencies-{{ checksum "package.json" }}
                - v1-dependencies-

            # Install project dependencies
            - run:
                name: Install local dependencies
                command: npm install && npm install --only=dev

            # Cache local dependencies if they don't exist
            - save_cache:
                key: v1-dependencies-{{ checksum "package.json" }}
                paths:
                    - node_modules

            - run:
                name: Building artifacts
                command: |
                    mkdir /tmp/artifacts
                    if [ "${CIRCLE_BRANCH}" == "staging" ]; then
                        npm run build-qa
                    elif [ "${CIRCLE_BRANCH}" == "master" ]; then
                        sudo npm install -g @angular/cli && ng build --prod
                        ls dist
                    else
                        npm run build-dev
                    fi
            
            - persist_to_workspace:
                root: .
                paths:
                    - .

            # Cache the dist folder for pther job
            - save_cache:
                key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
                paths:
                    - dist

            # - run:
            #     name: Compress Artifacts
            #     command: |
            #         zip -r council-search-app.zip dist


            - store_artifacts:
                path: dist
                destination: ~/project/council-search-app.zip

workflows:
    version: 2
    # the build workflow
    build_workflow:
        jobs:
            - build:
                filters:
                    branches:
                        only:
                            - master
